### ISSUE TITLE
windows10下无法复制到剪贴板

### ISSUE THREAD

**Issue by xunmeibuyue** [XboxYan/tree-generator#1]
你好，我觉得你的插件设计的很方便，但是我在Windows 10下使用的时候发现并不能复制到剪贴板，大概是extension.js中

`vscode.window.showInformationMessage(``♥︎目录树已经复制到剪贴板上了~``);`

这个语句应该都没有执行，猜测可能是`vscode.env.clipboard.writeText(str);`中出了问题，因为我的剪贴板中仍旧是上一次剪贴的内容。
希望对你完善这个插件有所帮助。
谢谢

**Comment by XboxYan** [comment]
@xunmeibuyue 感谢反馈，目前只在mac上测试过，回头看看windows上的表现

**Comment by XboxYan** [comment]
@xunmeibuyue 已修复
